extends: "default"

page:
  margin: [1in, 0.67in, 1in, 0.67in]
  numbering:
    start-at: 3

base:
  font-size: 11
  font-style: "normal"

heading:
  chapter:
    break-before: "always"

caption:
  font-style: "bold"

table:
  head:
    font-style: "bold"
    text-transform: "uppercase"

ulist:
  marker:
    font-size: 11

link:
  font-color: "#C00000"

role:
  # used for conformity
  compliant:
    font-color: "#28591C"
    font-style: "bold"

# used for non-conformity block
example:
  border-color: "#C00000"
  border-width: 1
  font-size: 11

